### PR TITLE
check if res is nil before check error

### LINKED ISSUE #1: Panic when json is invalid
If json is invalid then this error is triggered

```
goroutine 7 [running]:
        C:/Users/sdelacruz/Documents/go/src/github.com/tamerh/jsparser/jsparser.go:153 +0x29d
created by github.com/tamerh/jsparser.(*JsonParser).Stream
        C:/Users/sdelacruz/Documents/go/src/github.com/tamerh/jsparser/jsparser.go:70 +0x46
```

### PR DESCRIPTION
**Pull request by xhit**
Before check if error, first if res is nil. This avoid panic if json is invalid

Fixes #1

### CODE REVIEW

**Comment by tamerh** [comment]
Hello @xhit thanks for reporting the bug and PR. I think for complete fix when [getValueType](https://github.com/tamerh/jsparser/blob/b7e46d558ef241fd2ea1465445d7c1101ea4b023/jsparser.go#L671) func return `Invalid` it should trigger error like other errors. Because this func is used few other places too so this way will fix them as well.

**Comment by xhit** [comment]
In my json for test is not possible return Invalid with getValueType, and when res.Err is checking his value then res is nil, triggering a panic.

```json
{"list":[
          {"Name": true, "Text": "Knock knock."},
          {"Name": 4, "Text": "Who's there?"},
          {"Name": "Ed", "Text": "Go fmt."},
          {"Name": "Sam", "Text": "Go fm"t who?"},
          {"Name": "Ed", "Text": "Go fmt yourself!"}
]}
```

The optimal solution is check in parse always if res is nil and return, so I can get the err when Stream row:

```go
for row := range parser.Stream() {
          if row.Err != nil {
		log.Fatal(row.Err)
	}
}
```

sendError() set the channel the res with invalid json, and this is good, invalid is not caught, is setted and returned.

This fix works in this cases with invalid json, your fix proporal is for invalid values.

**Comment by tamerh** [comment]
All right I got your point. In addition to invalidity issue in the beginning of value in your case it is at the end means another issue for invalid json.  

But I would not go for nil result check because it is not identifying what went wrong and where. Instead i guess [this if](https://github.com/tamerh/jsparser/blob/b7e46d558ef241fd2ea1465445d7c1101ea4b023/jsparser.go#L260) needs else for sending error and also [this if ](https://github.com/tamerh/jsparser/blob/b7e46d558ef241fd2ea1465445d7c1101ea4b023/jsparser.go#L342) can be another else if in that if.

**Comment by xhit** [comment]
To know exact error is better make functions return the error, this need refactor this package. I think is possible to know the char index what breaks a json in an exact property with some ideas I have.

For now I going to left this solution because is possible to know the row index with bad property in the array without panic the app and doesn't need a strong refactor.

**Comment by tamerh** [comment]
All right then I close this PR and leave the bug report open I will fix these invalid cases in coming days.

**Pull request closed without merging**
